# Vanilla docker compose: consist only dockerwatcher

version: "3"
services:
  dockerwatcher:
    image: behradrvb/dockerwatcher:latest
    env_file:
    - .env
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock